name: DeepAden
channels:
  conda-forge
  defaults
dependencies:
  python=3.8.10
  numpy=1.20.3
  pandas=1.3.4
  tqdm=4.64.1
  biopython=1.81
  hmmer=3.3.2
  pip
pip:
  torch==2.1.0
  torch_geometric==2.5.0
  transformers==4.36.0
  peft==0.4.0
  tune-sklearn==0.5.0